### ISSUE TITLE
MFR-17 Artificer icon built into sheet

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#14]
**Feature Request:** Artificer icon built into sheet

**Extra information:** All official classes, but Artificer have icons as of beta 25, please could we get an icons for use next to character name?
**Who would use it?** Artificer players!
**How would it work?** Just include the icon as a choice like the other classes
**Why should this be added?** So Artificer characters don't feel left out and sad 🙂

- Smashman#1364

> Upvote - Smashman#1364

> Upvote - AelarTheElfRogue#3051

> Note - Smashman#1364

> Upvote - BoJack HorseBones#9942

> Upvote - Jimothy#3080

> Upvote - martyrcomplex#6969

> Upvote - Jonobi#6291

> Upvote - DivinitusRenes#0275

> Upvote - Izzy#4106

> Upvote - gaminggirl#4448

> Downvote - Azrael#5044

> Downvote - NeilGiraffeTyson#1618

> Downvote - Shepherd Book (DeathShooters)#0523

> Upvote - SCL#6788

> Downvote - Dig#6806

> Downvote - McChillster#2651

> Upvote - Ethan#5799

> Upvote - ZetaRESP#7456

> Upvote - ReyaktheHunter#5825

> Upvote - Shwaffle#1074

> Upvote - Laney#8129

> Upvote - MagmaKody#3314

> Upvote - Mach#0632

> Upvote - MarkM#6795

> Upvote - tylermc94#2589

> Upvote - ClaytonThomson#8031

> Upvote - FoulFagus#6969

> Upvote - Fuzzywuzzle#2295

> Upvote - MyriadMistress#0010

> Upvote - TomTheBoat#4304

> Upvote - Kevanishnu#0615

> Upvote - ARIZONA baby#1984

> Downvote - Xaniclos#1787

> Upvote - Hento#6542

> Upvote - uptownhuxyouup#9561

> Upvote - RainbowMagicMarker#2256

> Upvote - Malkav#2870

> Downvote - the-pieman#5849

> Upvote - babatazyah#2278

> Upvote - ChrisDF#9093

> Upvote - stewie828#1737

> Upvote - Snow#0308

> Upvote - ACwin#8322

> Downvote - Nerethil#2087

> Upvote - Garnett⚧Dawn#1873

> Upvote - GodlyPie#4644

> Upvote - swervmaster#5792

> Upvote - JMoo#9448

> Upvote - DwarfSpike#2687

> Downvote - Dport406#2494

> Upvote - aqueousErbium#1713

> Upvote - Domernicus#9316

> Upvote - DefaultProphet#6030

> Upvote - JakeTehPwner#0069

> Upvote - QQette#7751

> Upvote - Wismerhill#2123

> Downvote - TheDerangedWatermelon#4534

> Upvote - Diodric#1881

> Upvote - Hawaiiwong#2535

> Downvote - Linkin8er#9421

> Upvote - KoekKruimel#4576

> Upvote - Airground#3163

> Upvote - Sixon#0210

> Upvote - Vulcan#4906

> Downvote - Blue.Barracuda (Erik)#5671

> Upvote - Sock (emotional waves)#3534

Votes: +53 / -12

**Comment by crawltracker** [comment]
Note - morepurplemorebetter#1979

**Comment by morepurplemorebetter** [comment]
Because the crawltracker doesn't seem to add notes: This feature request has been implemented in v13.0.0beta26
