### ISSUE TITLE
MBUG-86 Spellsheet: empty lines are inserted between Class Header and Spell Header instead of after the last spell in the class section

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#170]
**What is the bug?**: Spellsheet: empty lines are inserted between Class Header and Spell Header instead of after the last spell in the class section
**Severity**: Low
**Steps to reproduce**: Fill the spellsheet with various class headers, spell headers and spells, make it overflow to a new page, observe odd placement of empty line, see screenshot
**Context**: MPBM v13.1.0+220114 (Printer Friendly - Redesign)

- jensgw#8811
Verification: 0

**Comment by spirritus** [comment]
![grafik](https://user-images.githubusercontent.com/1154316/154811565-ecc0726e-d75c-4846-90c2-dfcaf29de20a.png)

**Comment by crawltracker** [comment]
Note - morepurplemorebetter#1979

Resolved - Feature added in v13.1.2
