### ISSUE TITLE
MBUG-103 Multiclass spell slot count is wrong

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#189]
Version number of the sheet
13.1.4

Steps to reproduce
I made a caster, 5 levels order of the scribes wizard, 3 levels hexblade warlock, 2 levels clockwork soul sorcerer, with the atlas of endless horizons. The sheet appears to have given me one more 4th level spell slot than I should actually have for some reason.

- MartianPotato#8163
Verification: 0

**Comment by RisingValiant** [comment]
OP here, apologies, just tried to replicate the bug in a fresh sheet and it did not happen, could someone mark this as closed or however you go about that? My bad.

**Comment by crawltracker** [comment]
Note - MartianPotato#8163

Resolved - Ticket closed.
