### ISSUE TITLE
MBUG-9 Languages don't populate the alt-text/rollover-text when typed in the popup panel

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#41]
**What is the bug?**: Languages don't populate the alt-text/rollover-text when typed in the popup panel
**Severity**: Low
**Steps to reproduce**: Select background that gives a language proficiency (for example, Inheritor). Type in a language and confirm. When it loads and you hover over the language you learned from the background, it says ' "from Inheritor" language proficiency was gained from: Inheritor. '    The "from Inheritor" should be "Elvish". See accompanying picture.
**Context**: Also seen when adding languages from subclasses like Mastermind

![Screen_Shot_2020-05-13_at_10.16.39_AM.png](https://cdn.discordapp.com/attachments/554644051098337280/710180519354040321/Screen_Shot_2020-05-13_at_10.16.39_AM.png)

- Metacomet10#3669
Verification: 0

**Comment by Metacomet10** [comment]
Same for tool proficiencies
<img width="429" alt="Select Proficiency Popup" src="https://user-images.githubusercontent.com/6789837/81845641-b4dd5280-9505-11ea-9e92-d6898d650898.png">
<img width="429" alt="Tool Proficiency Alt-Text" src="https://user-images.githubusercontent.com/6789837/81845632-b1e26200-9505-11ea-9734-d75940e609e2.png">

**Comment by crawltracker** [comment]
Note - morepurplemorebetter#1979
