### ISSUE TITLE
MFR-006 Weapon Entries for Flame Blade and Shadow Blade

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#6]
**Feature Request:** Weapon Entries for Flame Blade and Shadow Blade

**Extra Information**

- Eru Ilúvatar#0962

> Note - Eru Ilúvatar#0962

> Note - Eru Ilúvatar#0962

> Upvote - AelarTheElfRogue#3051

> Upvote - Smashman#1364

> Upvote - RainbowMagicMarker#2256

> Downvote - safety-orange#4714

> Upvote - martyrcomplex#6969

> Upvote - Quaggy#5128

> Upvote - War*Profiteer*#2598

> Upvote - NeͥveͣrͫDead#9598

> Upvote - Hexygon#1618

> Upvote - Jontosaurus#0624

> Upvote - Kreek#3344

> Upvote - Dark Kijin#4414

> Upvote - Dorgrin#1585

> Upvote - Cloakedinvsion#7947

> Upvote - Bigfoot#2003

> Upvote - SudsNBubbles#1260

> Upvote - ReyaktheHunter#5825

> Upvote - Every1#2161

> Upvote - Shepherd Book (DeathShooters)#0523

> Upvote - BoJack HorseBones#9942

> Upvote - Ethan#5799

> Upvote - d0mmunism#9822

> Upvote - Quaazar#3864

> Upvote - Shiftingshadows#0913

> Upvote - virt_riff (Eric Heupel) (-4)#4484

> Upvote - Flamingkilla#6869

> Upvote - TikiPower#2180

> Upvote - InsanityOvrload#3672

> Upvote - mrpeach32#1766

> Upvote - Boylane#6145

> Upvote - gaminggirl#4448

> Upvote - Crazyfruit13#0013

> Upvote - bobsayshello#8844

> Upvote - the-pieman#5849

> Upvote - afrojohnw#6619

> Upvote - Azrael#5044

> Upvote - bevan7#0394

> Upvote - dilacerate#9956

> Upvote - sir tellabeem#5046

> Upvote - Joshy#3853

> Upvote - ActuallyASnake#0616

> Upvote - TC_Tunstall#1159

> Upvote - Navex#9615

> Upvote - Vezoth#1697

> Upvote - Dalgam#0957

> Upvote - Wismerhill#2123

> Upvote - Laney#8129

> Upvote - Grey#6454

> Upvote - Dr.Medic#8969

> Upvote - fallenone121#6144

> Upvote - Tackti#6625

> Upvote - dgjbfd#3069

> Upvote - warthog_smith#2372

> Downvote - KregularJoe#6699

> Downvote - PolyJohn#3758

> Upvote - Freaky Fox#6005

> Upvote - MarkM#6795

> Upvote - ChrisDF#9093

> Upvote - GrueWithNoLight#8150

> Upvote - VolcanicParrot#2531

> Upvote - seeme11#8986

> Upvote - Themis#2425

> Upvote - Jonobi#6291

> Upvote - DivinitusRenes#0275

> Upvote - Garnett⚧Dawn#1873

> Downvote - Dig#6806

> Upvote - Jolanarr#6261

> Upvote - Input#9984

> Upvote - Dash#6381

> Upvote - Sмιтнєяιησ#1116

> Upvote - ClaytonCross#0988

> Upvote - ARIZONA baby#1984

> Upvote - NeilGiraffeTyson#1618

> Upvote - Norl#6141

> Upvote - Nod_Hero#2046

> Upvote - Dport406#2494

> Upvote - Twilight#9133

> Upvote - Snow#0308

> Upvote - TomTheBoat#4304

> Upvote - 𝙅𝙪𝙨𝙩𝙌#5483

> Upvote - Nerethil#2087

> Upvote - Si#2835

> Upvote - adeumus#1746

> Upvote - DukePorkSword#2477

> Upvote - Blue.Barracuda (Erik)#5671

Votes: +81 / -4

**Comment by morepurplemorebetter** [comment]
Because the crawltracker doesn't seem to add notes: This feature request has been implemented in v13.0.0beta26, but only for the Shadow Blade, as that is the only spell for which it is applicable to have an attack entry as it works differently than all other spells.
