### ISSUE TITLE
MFR-7 Class Feature Variants for Revised Ranger

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#7]
**Feature Request:** Class Feature Variants for Revised Ranger

**Extra Information**
**Who would use it?** Everyone who still uses Revised Ranger (or is 40 sessions into a campaign and doesn't want their player to switch 😛)
**How would it work?** More or less the same as with PHB Ranger; presumably "Favored Foe" would have to replace both Favored Enemy and Greater Favored Enemy, but all the other features textually line up fine
**Why should this be added?** Most of the campaigns I've been in still use Revised Ranger, so it'd be nice to have access to the new features like spell versatility, primal beasts, and ESPECIALLY the new spells & fighting styles without having to fight with the sheet. (Also it carries on the tradition of us having voted for the XGtE subclasses to work with RR)

- martyrcomplex#6969

> Upvote - martyrcomplex#6969

> Upvote - Dig#6806

> Upvote - Vezoth#1697

> Upvote - Bergie31#2973

> Downvote - ActuallyASnake#0616

> Upvote - lancaster_dm#1609

> Upvote - Azrael#5044

> Downvote - BoJack HorseBones#9942

> Upvote - Freelancerjw#4763

> Upvote - Wismerhill#2123

> Upvote - Laney#8129

> Upvote - MagmaKody#3314

> Upvote - Satkaz#9906

> Downvote - Crazyfruit13#0013

> Downvote - DivinitusRenes#0275

> Downvote - Hento#6542

> Upvote - Every1#2161

> Upvote - fallenone121#6144

> Upvote - the-pieman#5849

> Upvote - Tackti#6625

> Upvote - SudsNBubbles#1260

> Upvote - dgjbfd#3069

> Upvote - warthog_smith#2372

> Upvote - Jontosaurus#0624

> Upvote - ReyaktheHunter#5825

> Upvote - Myrmadon#9813

> Downvote - PolyJohn#3758

> Downvote - MarkM#6795

> Downvote - Freaky Fox#6005

> Upvote - Ily#6518

> Upvote - Xanar50#8734

> Downvote - GrueWithNoLight#8150

> Upvote - Dioraptor#8098

> Downvote - McChillster#2651

> Upvote - Acthonon#0547

> Upvote - Larry Hoy#5790

> Upvote - Dunec#1296

> Upvote - Lamar#8301

> Upvote - Myoukochou#6588

> Upvote - VolcanicParrot#2531

> Upvote - Avor#6511

> Upvote - Boomer#2572

> Upvote - SaudFA#8063

> Upvote - buzzardoftheages#3745

> Upvote - Goth Harlot#1720

> Upvote - Jonobi#6291

> Downvote - Smashman#1364

> Upvote - swervmaster#5792

> Downvote - ClaytonThomson#8031

> Upvote - aqueousErbium#1713

> Upvote - Jolanarr#6261

> Upvote - SadSpaceMan#0002

> Upvote - Kevanishnu#0615

> Upvote - d0mmunism#9822

> Upvote - ARIZONA baby#1984

> Upvote - Kreek#3344

> Upvote - alphamine19#5059

> Upvote - Norl#6141

> Upvote - NeͥveͣrͫDead#9598

> Downvote - Nod_Hero#2046

> Downvote - Dport406#2494

> Upvote - Twilight#9133

> Downvote - ClaytonCross#0988

> Upvote - FoulFagus#6969

> Upvote - RainbowMagicMarker#2256

> Upvote - stewie828#1737

> Upvote - Nerethil#2087

> Upvote - Si#2835

> Upvote - Probear#6437

> Upvote - DefaultProphet#6030

> Upvote - Theobroma#9809

> Upvote - Linkin8er#9421

> Upvote - Airground#3163

> Downvote - AVestedInterest#2960

> Downvote - Blue.Barracuda (Erik)#5671

> Upvote - Sock (emotional waves)#3534

Votes: +59 / -17

**Comment by crawltracker** [comment]
Note - morepurplemorebetter#1979

**Comment by morepurplemorebetter** [comment]
Because the crawltracker doesn't seem to add notes: This feature request has been implemented in v13.0.0beta26
