### ISSUE TITLE
MBUG-33 The Letter size version of Colorful sheet on the website is corrupted and wont open

### ISSUE THREAD

**Issue by crawltracker** [flapkan/mpmb-tracker#85]
**What is the bug?**: The Letter size version of Colorful sheet on the website is corrupted and wont open
**Severity**: High
**Steps to reproduce**: Download the `MPMB’s Character Record Sheet (v13.0.5) [Colorful – Letter].pdf` file from <https://www.flapkan.com/>. Try to open in Acrobat Reader DC. 
**Context**: The error I get is: "There was an error opening this document. The file is damaged and could not be repaired." The same download, but from the pinned Patreon post opens fine. I am on macOS Catalina 10.15.7, with Reader DC version 2020.013.20074.

- Metacomet10#3669
Verification: 0

**Comment by Metacomet10** [comment]
Fixed on 1/29/21. Issue can be closed.

**Comment by crawltracker** [comment]
Note - morepurplemorebetter#1979

Resolved - corrupted files fixed on MPMB's website
